webpackJsonp([0x8deb0bb42b94],{575:function(n,r){n.exports={data:{markdownRemark:{html:'<p>[pre lang=js]function factorial(x){\n// Если x неправильное, генерируется исключение\nif(x&#x3C;0) throw new Error("X должно быть положительным");\nfor(var f=1; x>1; f*=x, x--);\n// Вычисление возвращаемого значения\nreturn f;\n};\ntry{\n// Приглашение ввести число\nvar n = Number(prompt("Введите число",""));\n// Вычисление факториала, исходя из предположения,\n// что введено правильное число\nvar f = factorial(n);\nalert(n + "! = " + f);\n}\ncatch (ex) { // Произошло исключение\nalert(ex); // Вывод сообщения об ошибке\n}[/pre]</p>\n<script>\nfunction factorial(x){\n// Если x неправильное, генерируется исключение\nif(x<0) throw new Error("X должно быть положительным");\nfor(var f=1; x>1; f*=x, x--);\n// Вычисление возвращаемого значения\nreturn f;\n};\ntry{\n// Приглашение ввести число\nvar n = Number(prompt("Введите число",""));\n// Вычисление факториала, исходя из предположения,\n// что введено правильное число\nvar f = factorial(n);\nalert(n + "! = " + f);\n}\ncatch (ex) { // Произошло исключение\nalert(ex); // Вывод сообщения об ошибке\n}\n</script>',frontmatter:{date:"2015-10-17",path:"/page/trycatch-javascript",title:"try/catch javascript"}}},pathContext:{}}}});
//# sourceMappingURL=path---page-trycatch-javascript-89b2d63e3b3ffae61381.js.map