{"version":3,"sources":["webpack:///path---page-trycatch-javascript-ef066742eca4cd660157.js","webpack:///./.cache/json/page-trycatch-javascript.json"],"names":["webpackJsonp","567","module","exports","data","markdownRemark","html","frontmatter","date","path","title","pathContext"],"mappings":"AAAAA,cAAc,iBAERC,IACA,SAAUC,EAAQC,GCHxBD,EAAAC,SAAkBC,MAAQC,gBAAkBC,KAAA,+hBAA6hBC,aAAgCC,KAAA,aAAAC,KAAA,4BAAAC,MAAA,0BAAwFC","file":"path---page-trycatch-javascript-ef066742eca4cd660157.js","sourcesContent":["webpackJsonp([156040653187988],{\n\n/***/ 567:\n/***/ (function(module, exports) {\n\n\tmodule.exports = {\"data\":{\"markdownRemark\":{\"html\":\"<pre><code>function factorial(x){\\n// Если x неправильное, генерируется исключение\\nif(x&#x3C;0) throw new Error(\\\"X должно быть положительным\\\");\\nfor(var f=1; x>1; f*=x, x--);\\n// Вычисление возвращаемого значения\\nreturn f;\\n};\\ntry{\\n// Приглашение ввести число\\nvar n = Number(prompt(\\\"Введите число\\\",\\\"\\\"));\\n// Вычисление факториала, исходя из предположения,\\n// что введено правильное число\\nvar f = factorial(n);\\nalert(n + \\\"! = \\\" + f);\\n}\\ncatch (ex) { // Произошло исключение\\nalert(ex); // Вывод сообщения об ошибке\\n}\\n</code></pre>\",\"frontmatter\":{\"date\":\"2015-10-17\",\"path\":\"/page/trycatch-javascript\",\"title\":\"try/catch javascript\"}}},\"pathContext\":{}}\n\n/***/ })\n\n});\n\n\n// WEBPACK FOOTER //\n// path---page-trycatch-javascript-ef066742eca4cd660157.js","module.exports = {\"data\":{\"markdownRemark\":{\"html\":\"<pre><code>function factorial(x){\\n// Если x неправильное, генерируется исключение\\nif(x&#x3C;0) throw new Error(\\\"X должно быть положительным\\\");\\nfor(var f=1; x>1; f*=x, x--);\\n// Вычисление возвращаемого значения\\nreturn f;\\n};\\ntry{\\n// Приглашение ввести число\\nvar n = Number(prompt(\\\"Введите число\\\",\\\"\\\"));\\n// Вычисление факториала, исходя из предположения,\\n// что введено правильное число\\nvar f = factorial(n);\\nalert(n + \\\"! = \\\" + f);\\n}\\ncatch (ex) { // Произошло исключение\\nalert(ex); // Вывод сообщения об ошибке\\n}\\n</code></pre>\",\"frontmatter\":{\"date\":\"2015-10-17\",\"path\":\"/page/trycatch-javascript\",\"title\":\"try/catch javascript\"}}},\"pathContext\":{}}\n\n\n//////////////////\n// WEBPACK FOOTER\n// ./~/json-loader!./.cache/json/page-trycatch-javascript.json\n// module id = 567\n// module chunks = 156040653187988"],"sourceRoot":""}